spring:
    kafka:
        consumer:
            group-id: ${KAFKA_GROUP_ID:hermeneut-consumer}
            bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# ===================================================================
# Kafka specific properties
# ===================================================================
kafka:
    topic:
        risk-profile: ${KAFKA_RISK_PROFILE_TOPIC:risk-profile-topic}
        criticality-notification: ${KAFKA_CRITICALITY_NOTIFICATION_TOPIC:criticality-notification-topic}
